
# NumPy exercises


In [279]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.0


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [280]:
# your code goes here
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



### Create a numpy array with values ranging from 10 to 49

In [281]:
# your code goes here
np.array(range(10,50))


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [282]:
# your code goes here
np.ones((2,2),dtype=int)


array([[1, 1],
       [1, 1]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [283]:
# your code goes here
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [284]:
# your code goes here
x = np.array([[1,5,10,4]])
np.full_like(x,1)

array([[1, 1, 1, 1]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [285]:
# your code goes here
x = np.array([[1,5],[6,8],[10,4]])
np.full_like(x,0)


array([[0, 0],
       [0, 0],
       [0, 0]])



### Create a numpy matrix of 4*4 integers, filled with fives.

In [286]:
# your code goes here
np.full((4,4),5)


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [287]:
# your code goes here
X = np.full((4,4),5)
np.full_like(X,7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])



### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [288]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [289]:
# your code goes here
np.random.randint(1,10,3)


array([6, 8, 4])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [290]:
# your code goes here
np.random.rand(3,3,3)

array([[[0.47679419, 0.36075931, 0.46390992],
        [0.49759745, 0.82745116, 0.66852269],
        [0.52819597, 0.11896201, 0.49053342]],

       [[0.04968979, 0.54864777, 0.62379925],
        [0.80564992, 0.14756806, 0.60643372],
        [0.25553793, 0.43852945, 0.81191315]],

       [[0.50645887, 0.45472787, 0.85761669],
        [0.37650576, 0.07842996, 0.35036106],
        [0.09986129, 0.34625472, 0.02403748]]])



### Given the X python list convert it to an Y numpy array

In [291]:
# your code goes here
x = [1,5,6,8,10,4]
np.array(x)


array([ 1,  5,  6,  8, 10,  4])



### Given the X numpy array, make a copy and store it on Y.

In [292]:
# your code goes here
x = np.array([1,5,6,8,10,4] )
y = np.copy(x)
print(y)


[ 1  5  6  8 10  4]




### Create a numpy array with numbers from 1 to 10

In [293]:
# your code goes here

np.array(range(1,11))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a numpy array with the odd numbers between 1 to 10

In [353]:
# your code goes here
np.array(range(0,10,2))


array([0, 2, 4, 6, 8])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [295]:
# your code goes here
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Show the memory size of the given Z numpy matrix

In [296]:
# your code goes here
z = np.arange(0,9).reshape(3,3)

z.nbytes



36

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [297]:
# your code goes here
x= np.array([1, 3, 5, 7, 9])
x[0]


1



### Given the X numpy array, show it's last element

In [354]:
# your code goes here
x= np.array([1, 3, 5, 7, 9])
x[-1]



9



### Given the X numpy array, show it's first three elements

In [355]:
# your code goes here
x= np.array([1, 3, 5, 7, 9])
x[:3]


array([1, 3, 5])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [300]:
# your code goes here
np.array(range(10,0,-1))


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])



### Given the X numpy array, show all middle elements

In [301]:
# your code goes here
x= np.array([1, 3, 5, 7, 9])
x[1:len(x)-1]


array([3, 5, 7])



### Given the X numpy array, show the elements in reverse position

In [302]:
# your code goes here
x= np.array([1, 3, 5, 7, 9])
x[::-1]


array([9, 7, 5, 3, 1])



### Given the X numpy array, show the elements in an odd position

In [303]:
# your code goes here
x= np.array([1, 3, 5, 7, 9])
x[1::2]


array([3, 7])



### Given the X numpy matrix, show the first row elements

In [356]:
# your code goes here
x= np.array([[1, 3], [5, 7],[2, 9]])

x[0]


array([1, 3])



### Given the X numpy matrix, show the last row elements

In [305]:
# your code goes here
x= np.array([[1, 3], [5, 7],[2, 9]])

x[:,-1]


array([3, 7, 9])



### Given the X numpy matrix, show the first element on first row

In [306]:
# your code goes here
x= np.array([[1, 3], [5, 7],[2, 9]])

x[0,0]


1



### Given the X numpy matrix, show the last element on last row

In [307]:
# your code goes here
x= np.array([[1, 3], [5, 7],[2, 9]])

x[-1,-1]


9



### Given the X numpy matrix, show the middle row elements

In [308]:
# your code goes here
x= np.array([[1,6,3], [5,5, 7],[2,15, 9]])

x[: , int(x.shape[1]/2)]


array([ 6,  5, 15])



### Given the X numpy matrix, show the first two elements on the first two rows

In [309]:
# your code goes here
x= np.array([[1,6,3], [5,5, 7],[2,15, 9]])

x[0:2 , 0:2]



array([[1, 6],
       [5, 5]])



### Given the X numpy matrix, show the last two elements on the last two rows

In [310]:
# your code goes here
x= np.array([[1,6,3], [5,5, 7],[2,15, 9]])

x[-2:: , -2:: ]


array([[ 5,  7],
       [15,  9]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [311]:
# your code goes here
x = np.array([[1,6,3,5,5, 7,2,15, 9]])
x.astype(float)

array([[ 1.,  6.,  3.,  5.,  5.,  7.,  2., 15.,  9.]])



### Reverse the given numpy array (first element becomes last)

In [312]:
# your code goes here
x = np.array([1,6,3,5,5, 7,2,15, 9])
np.flip(x)



array([ 9, 15,  2,  7,  5,  5,  3,  6,  1])



### Order (sort) the given numpy array

In [313]:
# your code goes here
x = np.array([1,6,3,5,5, 7,2,15, 9])
#sorted(x)
np.sort(x)


array([ 1,  2,  3,  5,  5,  6,  7,  9, 15])



### Given the X numpy array, set the fifth element equal to 1

In [314]:
# your code goes here
x = np.array([1,6,3,5,5, 7,2,15, 9])
x[4] = 1

x


array([ 1,  6,  3,  5,  1,  7,  2, 15,  9])



### Given the X numpy array, change the 50 with a 40

In [315]:
# your code goes here

x = np.array([1,6,3,5,50, 7,2,15, 50])
x[np.where(x==50)] = 40
x

array([ 1,  6,  3,  5, 40,  7,  2, 15, 40])


### Given the X numpy matrix, change the last row with all 1

In [316]:
# your code goes here
x= np.array([[1,6,3], [5,5, 7],[2,15, 9]])

x[: , -1]=1
x


array([[ 1,  6,  1],
       [ 5,  5,  1],
       [ 2, 15,  1]])


### Given the X numpy matrix, change the last item on the last row with a 0

In [317]:
# your code goes here
x= np.array([[1,6,3], [5,5, 7],[2,15, 9]])

x[-1, -1]=0
x


array([[ 1,  6,  3],
       [ 5,  5,  7],
       [ 2, 15,  0]])


### Given the X numpy matrix, add 5 to every element

In [318]:
# your code goes here
x= np.array([[1,6,3], [5,5, 7],[2,15, 9]])

np.add(x,5)

x+5

array([[ 6, 11,  8],
       [10, 10, 12],
       [ 7, 20, 14]])


## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [319]:
# your code goes here
x = np.array([1,6,-3,5,50, -7,2,-15, 50])

x<0





array([False, False,  True, False, False,  True, False,  True, False])


### Given the X numpy array, get the negative elements

In [383]:
# your code goes here
x = np.array([1,6,-3,5,50, -7,2,-15, 50])

y= x<0
print (x[y])

[ -3  -7 -15]



### Given the X numpy array, get numbers higher than 5

In [339]:
# your code goes here
x = np.array([1,6,-3,5,9, -7,2,-15, 50])

x[np.where(x>5)]


array([ 6,  9, 50])


### Given the X numpy array, get numbers higher than the elements mean

In [340]:
# your code goes here
x = np.array([1,6,-3,5,9, -7,2,-15, 50])
x[np.where(x>np.mean(x))]



array([ 6,  9, 50])


### Given the X numpy array, get numbers equal to 2 or 10

In [350]:
# your code goes here

x = np.array([1,6,-3,5,9, -7,2,-15, 10])
x[np.where((x == 2) |( x == 10))]

array([ 2, 10])


## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [352]:
# your code goes here
x = np.array([1,6,-3,5,9, -7,2,-15, 10])





## Summary statistics

### Given the X numpy array, show the sum of its elements

In [325]:
# your code goes here



### Given the X numpy array, show the mean value of its elements

In [326]:
# your code goes here



### Given the X numpy matrix, show the sum of its columns

In [327]:
# your code goes here



### Given the X numpy matrix, show the mean value of its rows

In [328]:
# your code goes here


### Given the X numpy array, show the max value of its elements

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



# Answer The following questions!

In [358]:
# your code goes here
import seaborn as sns

In [359]:

sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [376]:

df = sns.load_dataset('titanic')
df.head(20)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   
11         1       1  female  58.0      0      0  26.5500        S   First   
12         0       3    male  20.0      0      0   8.0500        S   Third   
13         0       3    male  39.0      1      5  31.2750        S   Third   
14         0       3  female  14.0      0      0   7.8542        S   Third   
15         1       2  female  55.0      0      0  16.0000        S  Second   
16         0       3    male   2.0      4      1  29.1250        Q   Third   
17         1       2    male   NaN      0      0  13.0000        S  Second   
18         0       3  female  31.0      1      0  18.0000        S   Third   
19         1       3  female   NaN      0      0   7.2250        C   Third   

      who  adult_male deck  embark_town alive  alone  
0     man        True  NaN  Southampton    no  False  
1   woman       False    C    Cherbourg   yes  False  
2   woman       False  NaN  Southampton   yes   True  
3   woman       False    C  Southampton   yes  False  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
6     man        True    E  Southampton    no   True  
7   child       False  NaN  Southampton    no  False  
8   woman       False  NaN  Southampton   yes  False  
9   child       False  NaN    Cherbourg   yes  False  
10  child       False    G  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
12    man        True  NaN  Southampton    no   True  
13    man        True  NaN  Southampton    no  False  
14  child       False  NaN  Southampton    no   True  
15  woman       False  NaN  Southampton   yes   True  
16  child       False  NaN   Queenstown    no  False  
17    man        True  NaN  Southampton   yes   True  
18  woman       False  NaN  Southampton    no  False  
19  woman       False  NaN    Cherbourg   yes   True

In [360]:
df = sns.load_dataset('titanic')

# Average age of woman category.

In [362]:
df[df.who=='woman'].age.mean()

32.0

## Average age of man category.

In [361]:
df[df.who=='man'].age.mean()

33.17312348668281

## The lowest age among alone woman.

In [363]:
df[df.who=='woman'].age.min()

16.0

# The highest pulse among running student and not fat category. 

In [374]:
df_ = sns.load_dataset('exercise')
df_.head(20)
df_[df.diet=='low fat'].pulse.max()

132

# Sort the DataFrame in ascending order of the 'age' use sort values (df.sort_values(by='...', ascending=...)). 

In [377]:
df.sort_values(by="age",ascending=True)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
803         1       3    male  0.42      0      1   8.5167        C   Third   
755         1       2    male  0.67      1      1  14.5000        S  Second   
644         1       3  female  0.75      2      1  19.2583        C   Third   
469         1       3  female  0.75      2      1  19.2583        C   Third   
78          1       2    male  0.83      0      2  29.0000        S  Second   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
859         0       3    male   NaN      0      0   7.2292        C   Third   
863         0       3  female   NaN      8      2  69.5500        S   Third   
868         0       3    male   NaN      0      0   9.5000        S   Third   
878         0       3    male   NaN      0      0   7.8958        S   Third   
888         0       3  female   NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  
803  child       False  NaN    Cherbourg   yes  False  
755  child       False  NaN  Southampton   yes  False  
644  child       False  NaN    Cherbourg   yes  False  
469  child       False  NaN    Cherbourg   yes  False  
78   child       False  NaN  Southampton   yes  False  
..     ...         ...  ...          ...   ...    ...  
859    man        True  NaN    Cherbourg    no   True  
863  woman       False  NaN  Southampton    no  False  
868    man        True  NaN  Southampton    no   True  
878    man        True  NaN  Southampton    no   True  
888  woman       False  NaN  Southampton    no  False  

[891 rows x 15 columns]